 import * as React from "react";
 import  { useState,useEffect } from 'react';
 import Banner from "../components/location-detail/banner";
 import Breadcrumb from "../components/location-detail/Breadcrumb"
 import Contact from "../components/location-detail/contact";
 import Nearby from "../components/location-detail/Nearby";
 import "../index.css";
 import {
   Template,
   GetPath,
   GetRedirects,
   TemplateConfig,
   TemplateProps,
   TemplateRenderProps,
   GetHeadConfig,
   HeadConfig,
 } from "@yext/pages";
 import PageLayout from "../components/PageLayout";
import Services from "../components/location-detail/Services";
import About from "../components/location-detail/About";
import Menu from "../components/location-detail/Menu";
import Model from "../components/location-detail/Model";
import { SearchHeadlessProvider } from "@yext/search-headless-react";
import Faciltites from "../components/location-detail/Facilities";
import dtl3 from "../images/dtl3.jpg"

import {
  Accordion,
  AccordionItem,
  AccordionItemHeading,
  AccordionItemButton,
  AccordionItemPanel,
} from 'react-accessible-accordion';
import   Nav  from "../components/Nav";
import Footer from "../components/footer";
import Faq from "../components/location-detail/Faq";
 
 export const config: TemplateConfig = {
   stream: {
     $id: "deepbluelocation",
     fields: [
      "id",
      "uid",
      "meta",
      "name",
      "mainPhone",
      "address",
      "description",
      "hours",
      "photoGallery",
      "slug",
      "yextDisplayCoordinate",
      "services",
      "neighborhood",
      "paymentOptions",
      "c_relatedFAQs.question",
      "c_documentFile",
      "c_documentURLDeepBlue1",
      "c_restaurantsServices1",
      "c_extraServiceAvailable1",
      "takeoutHours",
      "timezone",
      "c_deepBlueStoreMessage",
      "c_extraservices2",
      "deliveryHours",
      "dm_directoryParents.name",
      "dm_directoryParents.slug",
      "c_relatedmenuitemsdeepblue.c_menunav",
      "c_relatedmenuitemsdeepblue.name",
      "c_relatedmenuitemsdeepblue.slug",
      "c_relatedmenuitemsdeepblue.photoGallery",
      "c_relatedFAQs.answer"
     ],
     filter: {
      entityTypes: ["restaurant"],
     },
     localization: {
       locales: ["en"],
       primary: false,
     },
   },
 };

 export const getPath: GetPath<TemplateProps> = ({ document }) => {
   return `${document.slug.toString()}`;
 };
 
 export const getRedirects: GetRedirects<TemplateProps> = ({ document }) => {
   return [`index-old/${document.id.toString()}`];
 };
 
 export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({
   relativePrefixToRoot,
   path,
   document,
 }): HeadConfig => {
   return {
     title: document.name,
     charset: "UTF-8",
     viewport: "width=device-width, initial-scale=1",
     tags: [
       {
         type: "meta",
         attributes: {
           description: "This site was generated by the Yext SSG",
         },
       },
     ],
   };
 };
 
 const Location: Template<TemplateRenderProps> = ({
   relativePrefixToRoot,
   path,
   document,
 }) => {
   const {    
     name,
     address,
     hours,
     deliveryHours,
     takeoutHours,
     c_deepBlueStoreMessage,
     c_extraservices2,
     c_documentURLDeepBlue1,
     dm_directoryParents,
     c_extraServiceAvailable1,
     c_relatedmenuitemsdeepblue,
     services,
     c_relatedFAQs,
     mainPhone,
     yextDisplayCoordinate
   } = document;

   let preExpandedarr=[];

    if(c_relatedFAQs){
        c_relatedFAQs.map((e,i)=>{
            if(i==0){
                preExpandedarr=[e.question];            
            } 
        })
    }
    const[current,setCurrent]=useState('');
    function setclass(e){
      setCurrent(e.target.id)
    }

   return (
     <>
          <Nav />
          <Banner name={name} c_deepBlueStoreMessage={c_deepBlueStoreMessage}/>
          <Breadcrumb dm_directoryParents={dm_directoryParents} name={name}/>             
          <Contact address={address} name={name} c_documentURLDeepBlue1={c_documentURLDeepBlue1} c_extraservices2={c_extraservices2} phone={mainPhone} latitude={yextDisplayCoordinate.latitude}
          longitude={yextDisplayCoordinate.longitude} hours={hours} deliveryHours={deliveryHours} takeoutHours={takeoutHours}></Contact>
          <Services services={services}/>
          <About />
          {c_relatedmenuitemsdeepblue?
          <Menu c_relatedmenuitemsdeepblue={c_relatedmenuitemsdeepblue} c_documentURLDeepBlue1={c_documentURLDeepBlue1.uRL2} c_documentURLDeepBlue1prim={c_documentURLDeepBlue1.primaryCTA} name="Allergens"/>
                        :''}
          <Faciltites c_extraServiceAvailable1={c_extraServiceAvailable1} />
          {c_relatedFAQs?
          <Faq c_relatedFAQs={c_relatedFAQs}/>:''}
          
   {/* {c_relatedFAQs?
    <div className=" faq-sec w-full mt-0 lg:mt-36 xl:mt-52 relative  pb-9  before:shadow-[10px_3px_26px_rgba(0,0,0,0.10)] 
    before:border-opacity-5 before:bg-cover  before:bg-left before:bg-no-repeat before:bg-[#f8fafc] before:content-[''] z-0 before:block before:absolute before:top-0 before:left-0 before:lg:-left-1/2 before:xl:-left-[40%] before:w-full before:bottom-0 before:xl-bottom-10">
        <div className=" container-custom   mx-auto relative">
            <div className=" grid grid-cols-1 lg:grid-cols-2">
                  
            <h2 className=" text-optimabold block text-center lg:hidden text-[42px]  pt-10 xl:pt-8 pb-4 uppercase text-text-blue-dark ">FREQUENTLY ASKED QUESTIONS </h2>


<div className="relative order-1 lg:order-0 faq-sec-inner pr-0  lg:pr-20 xl:pr-6 pb-14  xl:pb-0">

    <h2 className=" text-optimabold hidden lg:block text-[42px] text-left pt-10 xl:pt-8 xl:pl-1 pb-4 uppercase text-text-blue-dark ">FREQUENTLY ASKED QUESTIONS </h2>
                    <div className="faq-tabs" >
                  
              {c_relatedFAQs.map((e,i)=>{
                
                  return(<>
                <div  className={`faq-tab py-0 mt-2  ${current==e.question?'current':''}`} >
                 <Accordion  preExpanded={preExpandedarr}>
                 {e.question? <AccordionItem uuid={e.question}>
                <AccordionItemHeading>
                    <AccordionItemButton>
                    <h3 id={e.question} className="faq-tab-label  border-[1px] !text-base   border-[#3A78B7]  !p-2 " onClick={setclass}>{e.question}</h3>
                    </AccordionItemButton>
                </AccordionItemHeading>
                <AccordionItemPanel>
                <div className="faq-tab-content">
                  {e.answer}
                </div>
                </AccordionItemPanel>
               </AccordionItem>:''}
              </Accordion>
              </div>  
                  </>)
              })}  
      </div>
      <div className="text-center  absolute bottom-0 xl:bottom-0 left-0 w-full pr-0  lg:pr-16"> <a href="#" class="bg-blue-primary mt-4  xl:mt-0 uppercase  px-5
                         text-white hover:text-white text-sm !leading-9 text-center
                        inline-block rounded-sm text-main-blue   w-[163px]
                        hover:transition-all transform hover:scale-[1.09]"> view more </a> </div>

   </div>
<div className="relative  order-0 lg:order-1  right-0 mt-4 px-4 lg:px-0 mt-0 lg:-mt-10  xl:-mt-36 lg:-ml-14 xl:ml-6">
<img className="rounded-tl-2xl w-full rounded-br-2xl  " src={dtl3} alt=""/>
    </div>
    </div>
    </div>
    </div>
:''}  */}
          <Nearby latitude={yextDisplayCoordinate.latitude} longitude={yextDisplayCoordinate.longitude}/>     
    <Footer/>


     </>
   );
 };
 
 export default Location;
 